
name: Deploy Docs
run-name: ${{ github.actor }} is Running ðŸš€
on: 
  push:
    tags:
      - v*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true

      # - name: Restore Build Result
      #   uses: actions/download-artifact@v7
      #   with:
      #     name: build-result

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 # Use a recent version of pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install Deps
        run: |
          pnpm install --no-frozen-lockfile
        
      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=16384
        run: |-
          pnpm run build
        
#      - name: Combine output
#        run: |
#          pnpm cpx "src/.vuepress/dist/**" dist
#          pnpm cpx "docs/freecodecamp-org/dist/**" dist/freecodecamp.org
#          pnpm cpx "docs/hackingwithswfit-com/dist/**" dist/hackingwithswfit.com

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Deploy Docs
          branch: gh-pages
          # folder: dist
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true
